// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwpkcnvypzyatnbwbcob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3cGtjbnZ5cHp5YXRuYndiY29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODU0OTAsImV4cCI6MjA2NDM2MTQ5MH0.5rRJX8k2AIFfoSYJb4MSaXkgAnwtmi6K7Gw3eZ2WK8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);